# -*- coding: utf-8 -*-
"""ppt-direct demo deck — 3 slides built purely with the public generator_skeleton helpers."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ppt-direct", "templates"))
from generator_skeleton import *

OUT = os.path.join(os.path.dirname(__file__), "demo_work", "demo_deck.pptx")
prs, blank = new_prs()

# Slide 1 — dark divider
s = prs.slides.add_slide(blank)
divider(s, "01", "From plain text to a vector deck", "The model designs, python-pptx renders — no templates, no drag-and-drop")

# Slide 2 — light data page
s = prs.slides.add_slide(blank)
page_bg(s, BG_L)
header(s, "PART 01", "Quarterly Growth Snapshot", "Fictional demo data · generated by /ppt-direct in one pass")
hbar_rows(s, [
    ("North America", "Q1 $1.2M", "Q2 $1.8M", 150, "+50%", "up"),
    ("Europe",        "Q1 $0.9M", "Q2 $1.1M", 122, "+22%", "up"),
    ("APAC",          "Q1 $1.5M", "Q2 $1.4M", 140, "-7%",  "down"),
])
footer(s, note="ppt-direct demo · fictional data", date="2026-09")

# Slide 3 — closing
s = prs.slides.add_slide(blank)
page_bg(s, NAVY)
circle(s, 9.8, 4.2, 5.2, color=BLUE, alpha=0.12)
text(s, 0.9, 2.9, 11.5, 1.2, "Ship your story,\nnot your weekend.", 44, WHITE, bold=True)
rect(s, 0.95, 5.1, 1.2, 0.06, ORANGE)
text(s, 0.95, 5.35, 10.0, 0.5, "github.com/xu-jin-cs/ppt-skills", 15, "AAB4D8")

prs.save(OUT)
print("saved:", OUT)
